"""add daily_chat_metrics table

Revision ID: ae1f6fd84fde
Revises: 5a6f9439efbb
Create Date: 2026-07-20 16:31:34.349569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1f6fd84fde'
down_revision: Union[str, Sequence[str], None] = '5a6f9439efbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_chat_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('avg_tokens', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('daily_active_users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'user_id', name='uq_date_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_chat_metrics')
    # ### end Alembic commands ###
